Fix: add values.schema.json validation
splunk/splunk-connect-for-snmp pull request #1028
Opened 2024-06-05 10:36 UTC by wojtekzyla

# Description

This PR adds values.schema.json to validate `values.yaml` in helm chart

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Refactor/improvement

## How Has This Been Tested?

Manual testing

## Checklist

- [ ] My commit message is [conventional](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [ ] I have run pre-commit on all files before creating the PR
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2024-06-10 09:11 UTC, ajasnosz requested changes

2024-06-10 09:11 UTC, ajasnosz commented on charts/splunk-connect-for-snmp/values.schema.json
> +      "type": "object"
I think I would just allow to configure repository, pullPolicy and tag for mibserver

2024-06-10 11:43 UTC, wojtekzyla commented on charts/splunk-connect-for-snmp/values.schema.json
> +    "splunk": {
I was thinking about it. The problem is that if someone wants to use only o11y without a splunk, then these are not required. However they are still provided in the values.yaml from charts as empty strings so we could change it `required`

2024-06-10 11:48 UTC, wojtekzyla commented on charts/splunk-connect-for-snmp/values.schema.json
> +        },
The syntax we use here is a multiline string. The `|` sign indicates the beginning of the multiline string ([helm documentation](https://helm.sh/docs/chart_template_guide/yaml_techniques/#strings-in-yaml)). This string is the pasted into the `config.yaml` file in configmap

```
profiles: |
    smart_profile:
      frequency: 100
      condition:
        type: field
        field: "SNMPv2-MIB.sysDescr"
        patterns:
          - '.*linux.*'
      varBinds:
        - ['SNMPv2-MIB']
        - ['SNMPv2-MIB', 'sysName']
        - ['SNMPv2-MIB', 'sysUpTime',0]
```

2024-06-10 13:47 UTC, ajasnosz requested changes

2024-06-13 13:39 UTC, wojtekzyla commented on examples/lightweight_installation.yaml
> +  token: ""###SPLUNK_TOKEN###"
fixed

2024-06-17 12:08 UTC, ajasnosz approved these changes
Add changelog

2024-06-17 12:32 UTC, merged

2024-06-17 12:38 UTC, srv-rr-github-token commented
:tada: This PR is included in version 1.11.0-beta.9 :tada:

The release is available on [GitHub release](https://github.com/splunk/splunk-connect-for-snmp/releases/tag/v1.11.0-beta.9)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: