fix: pysnmp debug mode
splunk/splunk-connect-for-snmp pull request #1069
Opened 2024-09-02 13:25 UTC by ikheifets-splunk

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Dependency update
- [ ] Bug fix
- [ ] New feature
- [ ] Refactor/improvement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist

- [ ] My commit message is [conventional](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [ ] I have run pre-commit on all files before creating the PR
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2024-09-03 06:33 UTC, ajasnosz requested changes
Run 'make render' in repository and add updated files.

2024-09-03 06:33 UTC, ajasnosz commented on splunk_connect_for_snmp/snmp/manager.py
> +    debug.setLogger(debug.Debug('all', options={'loggerName': logger}))
I'm debating whether to add also parameter to set which logs we want, instead of always having 'all'. What do you think?

2024-09-09 11:32 UTC, ikheifets-splunk commented on charts/splunk-connect-for-snmp/templates/traps/deployment.yaml
> +            - name: PYSNMP_DEBUG
traps haven't `_helper.tpl` like have workers that can reuse it, by this reason for traps it on deployment

2024-09-09 13:17 UTC, ikheifets-splunk commented on splunk_connect_for_snmp/traps.py
> -logging.basicConfig(
transforming `logging` to `logger` for passing it to `debug mode`

2024-09-10 11:54 UTC, ajasnosz approved these changes

2024-09-10 11:56 UTC, ajasnosz requested changes
run precommit to fix issues

2024-09-17 08:29 UTC, merged

2024-09-17 08:35 UTC, srv-rr-github-token commented
:tada: This PR is included in version 1.11.1-beta.2 :tada:

The release is available on [GitHub release](https://github.com/splunk/splunk-connect-for-snmp/releases/tag/v1.11.1-beta.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: