fix: add logs in traps server for situations when incoming traps have…
splunk/splunk-connect-for-snmp pull request #953
Opened 2024-02-07 09:08 UTC by wojtekzyla

… wrong credentials

fix: delete unwanted files

fix: add logging of source device ip

fix: log only necessary info

fix: run pre-commit

fix: update the troubleshooting documentation

# Description

This PR adds logging for snmp traps errors

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Refactor/improvement

## How Has This Been Tested?

Manual testing

## Checklist

- [ ] My commit message is [conventional](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [ ] I have run pre-commit on all files before creating the PR
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2024-02-07 11:33 UTC, ajasnosz requested changes

2024-02-07 11:33 UTC, ajasnosz commented on docs/bestpractices.md
> +The first possible answer to why traps aren't sent to Splunk is that SNMP agents send trap messages to the wrong IP
I would add here a subtitle with as to any other problem that's _Wrong IP or port_ . Also let's not use short forms in documentation like _aren't_ etc.

2024-02-07 11:33 UTC, ajasnosz commented on docs/bestpractices.md
> +
Maybe we could add general section about logs (not only for traps) in Peaces of Advice, so it would be easier to find how to see logs.

2024-02-07 11:33 UTC, ajasnosz commented on docs/bestpractices.md
> +#### Error messages for different authentication problems
I don't think we have to add that as section

2024-02-07 11:33 UTC, ajasnosz commented on docs/bestpractices.md
> +##### Wrong community string
Let's follow pattern of previous issues, and have the error message as title. I think it's easier to find for someone searching for solution.

2024-02-07 11:33 UTC, ajasnosz commented on docs/bestpractices.md
> +`public` community configuration:
See the following example of a ...
We could use that phase with every example

2024-02-07 11:33 UTC, ajasnosz commented on docs/bestpractices.md
> +After creating the secret, add it under `traps.usernameSecrets` in `values.yaml`. Also make sure, that the correct snmp engine id
without also

2024-02-07 11:33 UTC, ajasnosz commented on docs/bestpractices.md
> +If this error occurs, make sure that the kubernetes secret with the correct username has been created ([SNMPv3 configuration](configuration/snmpv3-configuration.md)).
make sure -> verify?
I think this phrase is in every other section, so let's change there too

2024-02-07 11:56 UTC, wojtekzyla commented on splunk_connect_for_snmp/traps.py
> +
you're right, I forgot to delete it

2024-02-07 14:25 UTC, ajasnosz requested changes

2024-02-07 14:25 UTC, ajasnosz commented on docs/bestpractices.md
> +In case agents send traps to the correct address, but there is still no data in the `netops` index, there might some
might **be** some

2024-02-07 14:25 UTC, ajasnosz commented on docs/bestpractices.md
> +After creating the secret, add it under `traps.usernameSecrets` in `values.yaml`. Make sure, that the correct snmp engine id
I would change this make sure to Verify or Check

2024-02-07 14:25 UTC, ajasnosz commented on docs/bestpractices.md
> +##### Unknown SNMP security name encountered
There should be 4# for this title - similar issue for the titles below

2024-02-08 09:16 UTC, merged

2024-02-08 09:22 UTC, srv-rr-github-token commented
:tada: This PR is included in version 1.10.0-beta.4 :tada:

The release is available on [GitHub release](https://github.com/splunk/splunk-connect-for-snmp/releases/tag/v1.10.0-beta.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: